name: wkx-photo-watermark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - PySide6>=6.6
      - Pillow>=10.0
      - piexif>=1.1.3
      - pyinstaller>=6.0